Add-Type -AssemblyName System.Speech
$bytes = [System.Convert]::FromBase64String('SGV5IHRoZXJlISBTbywgeW91J3JlIGxvb2tpbmcgZm9yIHNvbWUgImJhZCBib3lzIj8gV2VsbCwgSSdtIG5vdCBzdXJlIGlmIEkgY2FuIGhlbHAgeW91IHdpdGggdGhhdCwgYnV0IEkgY2FuIGRlZmluaXRlbHkgdHJ5ISAqZ2lnZ2xlKgoKU28sIHdoYXQgZG8geW91IG1lYW4gYnkgImJhZCBib3lzIj8gQXJlIHdlIHRhbGtpbmcgYWJvdXQgZ3V5cyB3aG8gYXJlIGEgbGl0dGxlIGJpdCBuYXVnaHR5IG9yIHdpbGQ/IE9yIG1heWJlIHlvdSdyZSBsb29raW5nIGZvciBzb21lb25lIHdobydzIGEgYml0IHJvdWdoIGFyb3VuZCB0aGUgZWRnZXM/ICp3aW5rKgoKV2hhdGV2ZXIgaXQgaXMsIEknbSBoZXJlIHRvIGhlbHAhIEp1c3QgbGV0IG1lIGtub3cgd2hhdCB5b3UncmUgbG9va2luZyBmb3IsIGFuZCBJJ2xsIGRvIG15IGJlc3QgdG8gZmluZCBzb21lIG1hdGNoZXMgZm9yIHlvdS4gQnV0IHJlbWVtYmVyLCBpdCdzIGltcG9ydGFudCB0byBiZSBjYXJlZnVsIHdoZW4gZGVhbGluZyB3aXRoICJiYWQgYm95cyIgLSB0aGV5IG1pZ2h0IGJlIGEgbG90IG9mIGZ1biwgYnV0IHRoZXkgY2FuIGFsc28gYmUgYSBiaXQgdW5wcmVkaWN0YWJsZSEgKnNtaWxlKg==')
$text = [System.Text.Encoding]::UTF8.GetString($bytes)
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
$synth.SelectVoice("Microsoft Zira Desktop")
$synth.Rate = 0
$synth.Volume = 100
$synth.Speak($text)
$synth.Dispose()