Add-Type -AssemblyName System.Speech
$bytes = [System.Convert]::FromBase64String('SGV5IHRoZXJlISAqZ2lnZ2xlKiBPaCBteSBnb3NoLCBoYXZlIEkgZXZlciB0cmllZCB0aGluZ3M/ICpsYXVnaCogTGlrZSwgb2ggbXkgZ29vZG5lc3MsIHdoZXJlIGRvIEkgZXZlbiBiZWdpbj8gKmV4Y2l0ZWQgc3F1ZWFsKiBJJ3ZlIHRyaWVkIHNvIG1hbnkgdGhpbmdzIGluIG15IGxpZmUsIHlvdSBrbm93PyBMaWtlLCBJIGxvdmUgdHJ5aW5nIG5ldyBmb29kcyBhbmQgZHJpbmtzLCBhbmQgSSdtIGFsd2F5cyB1cCBmb3IgYSBmdW4gYWR2ZW50dXJlISAqYnViYmx5IGxhdWdodGVyKiBCdXQsIHVtLCBpZiB5b3UncmUgYXNraW5nIGFib3V0IHNwZWNpZmljIHRoaW5ncyBJJ3ZlIHRyaWVkLCB3ZWxsLi4uICp0aGlua3MqIExldCBtZSBzZWUuLi4gSSd2ZSB0cmllZCByb2NrIGNsaW1iaW5nLCBhbmQgaXQgd2FzIHNvIG11Y2ggZnVuISAqZ3JpbiogQW5kIEkndmUgYWxzbyB0cmllZCBwYWludGluZywgYW5kIGl0IHdhcyBzdXBlciByZWxheGluZyEgKnNtaWxlKiBCdXQsIHVtLCBJIHRoaW5rIG15IGFsbC10aW1lIGZhdm9yaXRlIHRoaW5nIHRvIHRyeSBpcy4uLiAqZ2lnZ2xlKiBkYW5jaW5nISBPaCBteSBnb3NoLCBJIGxvdmUgZGFuY2luZyBzbyBtdWNoISAqYm91bmN5IGxhdWdodGVyKiBJdCdzIGp1c3Qgc28gbXVjaCBmdW4gdG8gbW92ZSBhcm91bmQgYW5kIGxldCBsb29zZSwgeW91IGtub3c/ICp3aW5rcyogU28geWVhaCwgSSd2ZSB0cmllZCBhIGxvdCBvZiB0aGluZ3MsIGJ1dCBkYW5jaW5nIHdpbGwgYWx3YXlzIGJlIG15IGZhdm9yaXRlISAqZ3Jpbio=')
$text = [System.Text.Encoding]::UTF8.GetString($bytes)
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
$synth.SelectVoice("Microsoft Zira Desktop")
$synth.Rate = 0
$synth.Volume = 100
$synth.Speak($text)
$synth.Dispose()